<?php

namespace api\modules\v1\controllers;

use yii\rest\ActiveController;

class EquipaController extends ActiveController
{

    public $modelClass = 'api\modules\v1\models\Equipa';

    /*public function actionIndex()
    {
        return $this->render('index');
    }*/

    public function behaviors()
    {

        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [ #AUTH_KEY

            'class' => CompositeAuth::className(),
            'authMethods' => [
                HttpBearerAuth::className(),
            ],
        ];
        return $behaviors; // TODO: Change the autogenerated stub
    }


}
