<?php

namespace api\modules\v1\controllers;

use Yii;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\QueryParamAuth;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\rest\ActiveController;
use common\models\User;

class UserController extends ActiveController
{

    public $modelClass = 'common\models\User';

    //Cria outro user controller um sem autenticacao para fazer o login na aplicação android

    /*public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator']=[
            'class' => HttpBasicAuth::className(),
            'auth' => function($username, $password)
            {
                $user = User::findByUsername($username);
                if($user && $user->validatePassword($password))
                {
                    return $user;
                }
            }
        ];
        return $behaviors; // TODO: Change the autogenerated stub
    }*/

    public function actionLogin(){
        $user = User::findByUsername(Yii::$app->request->post('username'));
        if($user->validatePassword(Yii::$app->request->post('password'))){
            return $user;
        }
        return ["Error"];
    }

    public function actionRegisto(){
        $user = new User();
        $user-> username = yii::$app->request->post('username');
        $user-> nome = yii::$app->request->post('nome');
        $user-> dataNascimento = yii::$app->request->post('dataNascimento');
        $user-> email = yii::$app->request->post('email');
        $user-> nacionalidade = yii::$app->request->post('nacionalidade');
        $user->setPassword(Yii::$app->request->post('password'));
        $user->generateAuthKey();

        if($user->validate()){
            $user->save();
            $auth = \Yii::$app->authManager;
            $regularRole = $auth->getRole('regular');
            $auth->assign($regularRole, $user->getId());
            return $user;
        }

        return ["Error"];

    }

}
